spring:
  datasource:
    url: jdbc:h2:file:~/bank-db
    username: user
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2

logging:
  level:
    com.demo: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: ./application.log
